class AsmaulHusnaModel {
  final int number;
  final String arabic;
  final String transliteration;
  final String meaning;

  const AsmaulHusnaModel({
    required this.number,
    required this.arabic,
    required this.transliteration,
    required this.meaning,
  });
}

const List<AsmaulHusnaModel> allNames = [
  AsmaulHusnaModel(number: 1, arabic: 'اللَّهُ', transliteration: 'Allah', meaning: 'The One God / একমাত্র আল্লাহ'),
  AsmaulHusnaModel(number: 2, arabic: 'الرَّحْمَنُ', transliteration: 'Ar-Rahman', meaning: 'The Most Gracious / পরম দয়ালু'),
  AsmaulHusnaModel(number: 3, arabic: 'الرَّحِيمُ', transliteration: 'Ar-Rahim', meaning: 'The Most Merciful / বিশেষ দয়ালু'),
  AsmaulHusnaModel(number: 4, arabic: 'الْمَلِكُ', transliteration: 'Al-Malik', meaning: 'The King / রাজাধিরাজ'),
  AsmaulHusnaModel(number: 5, arabic: 'الْقُدُّوسُ', transliteration: 'Al-Quddus', meaning: 'The Most Holy / পবিত্রতম'),
  AsmaulHusnaModel(number: 6, arabic: 'السَّلَامُ', transliteration: 'As-Salam', meaning: 'The Source of Peace / শান্তির উৎস'),
  AsmaulHusnaModel(number: 7, arabic: 'الْمُؤْمِنُ', transliteration: 'Al-Mu\'min', meaning: 'The Guardian of Faith / বিশ্বাসের রক্ষক'),
  AsmaulHusnaModel(number: 8, arabic: 'الْمُهَيْمِنُ', transliteration: 'Al-Muhaymin', meaning: 'The Overseer / সর্বনিয়ন্ত্রক'),
  AsmaulHusnaModel(number: 9, arabic: 'الْعَزِيزُ', transliteration: 'Al-Aziz', meaning: 'The Almighty / পরাক্রমশালী'),
  AsmaulHusnaModel(number: 10, arabic: 'الْجَبَّارُ', transliteration: 'Al-Jabbar', meaning: 'The Compeller / মহাশক্তিমান'),
  AsmaulHusnaModel(number: 11, arabic: 'الْمُتَكَبِّرُ', transliteration: 'Al-Mutakabbir', meaning: 'The Supreme / মহাগর্বিত'),
  AsmaulHusnaModel(number: 12, arabic: 'الْخَالِقُ', transliteration: 'Al-Khaliq', meaning: 'The Creator / সৃষ্টিকর্তা'),
  AsmaulHusnaModel(number: 13, arabic: 'الْبَارِئُ', transliteration: 'Al-Bari\'', meaning: 'The Originator / উদ্ভাবক'),
  AsmaulHusnaModel(number: 14, arabic: 'الْمُصَوِّرُ', transliteration: 'Al-Musawwir', meaning: 'The Fashioner / রূপদানকারী'),
  AsmaulHusnaModel(number: 15, arabic: 'الْغَفَّارُ', transliteration: 'Al-Ghaffar', meaning: 'The Ever-Forgiving / মহাক্ষমাশীল'),
  AsmaulHusnaModel(number: 16, arabic: 'الْقَهَّارُ', transliteration: 'Al-Qahhar', meaning: 'The All-Subduer / সর্বজয়ী'),
  AsmaulHusnaModel(number: 17, arabic: 'الْوَهَّابُ', transliteration: 'Al-Wahhab', meaning: 'The Bestower / মহাদাতা'),
  AsmaulHusnaModel(number: 18, arabic: 'الرَّزَّاقُ', transliteration: 'Ar-Razzaq', meaning: 'The Provider / রিজিকদাতা'),
  AsmaulHusnaModel(number: 19, arabic: 'الْفَتَّاحُ', transliteration: 'Al-Fattah', meaning: 'The Opener / উদ্ঘাটনকারী'),
  AsmaulHusnaModel(number: 20, arabic: 'الْعَلِيمُ', transliteration: 'Al-\'Alim', meaning: 'The All-Knowing / সর্বজ্ঞ'),
  AsmaulHusnaModel(number: 21, arabic: 'الْقَابِضُ', transliteration: 'Al-Qabid', meaning: 'The Withholder / সংকোচনকারী'),
  AsmaulHusnaModel(number: 22, arabic: 'الْبَاسِطُ', transliteration: 'Al-Basit', meaning: 'The Extender / প্রসারণকারী'),
  AsmaulHusnaModel(number: 23, arabic: 'الْخَافِضُ', transliteration: 'Al-Khafid', meaning: 'The Reducer / অবনতকারী'),
  AsmaulHusnaModel(number: 24, arabic: 'الرَّافِعُ', transliteration: 'Ar-Rafi\'', meaning: 'The Exalter / উন্নয়নকারী'),
  AsmaulHusnaModel(number: 25, arabic: 'الْمُعِزُّ', transliteration: 'Al-Mu\'izz', meaning: 'The Honourer / সম্মানদানকারী'),
  AsmaulHusnaModel(number: 26, arabic: 'الْمُذِلُّ', transliteration: 'Al-Mudhil', meaning: 'The Dishonorer / অপমানকারী'),
  AsmaulHusnaModel(number: 27, arabic: 'السَّمِيعُ', transliteration: 'As-Sami\'', meaning: 'The All-Hearing / সর্বশ্রোতা'),
  AsmaulHusnaModel(number: 28, arabic: 'الْبَصِيرُ', transliteration: 'Al-Basir', meaning: 'The All-Seeing / সর্বদ্রষ্টা'),
  AsmaulHusnaModel(number: 29, arabic: 'الْحَكَمُ', transliteration: 'Al-Hakam', meaning: 'The Judge / বিচারক'),
  AsmaulHusnaModel(number: 30, arabic: 'الْعَدْلُ', transliteration: 'Al-\'Adl', meaning: 'The Just / ন্যায়পরায়ণ'),
  AsmaulHusnaModel(number: 31, arabic: 'اللَّطِيفُ', transliteration: 'Al-Latif', meaning: 'The Subtle / সূক্ষ্মদর্শী'),
  AsmaulHusnaModel(number: 32, arabic: 'الْخَبِيرُ', transliteration: 'Al-Khabir', meaning: 'The All-Aware / সম্যক অবগত'),
  AsmaulHusnaModel(number: 33, arabic: 'الْحَلِيمُ', transliteration: 'Al-Halim', meaning: 'The Forbearing / সহনশীল'),
  AsmaulHusnaModel(number: 34, arabic: 'الْعَظِيمُ', transliteration: 'Al-\'Azim', meaning: 'The Magnificent / মহামহিম'),
  AsmaulHusnaModel(number: 35, arabic: 'الْغَفُورُ', transliteration: 'Al-Ghafur', meaning: 'The Forgiving / ক্ষমাশীল'),
  AsmaulHusnaModel(number: 36, arabic: 'الشَّكُورُ', transliteration: 'Ash-Shakur', meaning: 'The Appreciative / কৃতজ্ঞতা স্বীকারকারী'),
  AsmaulHusnaModel(number: 37, arabic: 'الْعَلِيُّ', transliteration: 'Al-\'Ali', meaning: 'The Most High / সর্বোচ্চ'),
  AsmaulHusnaModel(number: 38, arabic: 'الْكَبِيرُ', transliteration: 'Al-Kabir', meaning: 'The Greatest / সর্বমহান'),
  AsmaulHusnaModel(number: 39, arabic: 'الْحَفِيظُ', transliteration: 'Al-Hafiz', meaning: 'The Preserver / সংরক্ষণকারী'),
  AsmaulHusnaModel(number: 40, arabic: 'الْمُقِيتُ', transliteration: 'Al-Muqit', meaning: 'The Nourisher / পালনকর্তা'),
  AsmaulHusnaModel(number: 41, arabic: 'الْحَسِيبُ', transliteration: 'Al-Hasib', meaning: 'The Reckoner / হিসাবগ্রহণকারী'),
  AsmaulHusnaModel(number: 42, arabic: 'الْجَلِيلُ', transliteration: 'Al-Jalil', meaning: 'The Majestic / মহাপ্রতাপশালী'),
  AsmaulHusnaModel(number: 43, arabic: 'الْكَرِيمُ', transliteration: 'Al-Karim', meaning: 'The Generous / মহাউদার'),
  AsmaulHusnaModel(number: 44, arabic: 'الرَّقِيبُ', transliteration: 'Ar-Raqib', meaning: 'The Watchful / পর্যবেক্ষণকারী'),
  AsmaulHusnaModel(number: 45, arabic: 'الْمُجِيبُ', transliteration: 'Al-Mujib', meaning: 'The Responsive / সাড়াদানকারী'),
  AsmaulHusnaModel(number: 46, arabic: 'الْوَاسِعُ', transliteration: 'Al-Wasi\'', meaning: 'The All-Encompassing / সর্বব্যাপী'),
  AsmaulHusnaModel(number: 47, arabic: 'الْحَكِيمُ', transliteration: 'Al-Hakim', meaning: 'The Wise / মহাজ্ঞানী'),
  AsmaulHusnaModel(number: 48, arabic: 'الْوَدُودُ', transliteration: 'Al-Wadud', meaning: 'The Loving / প্রেমময়'),
  AsmaulHusnaModel(number: 49, arabic: 'الْمَجِيدُ', transliteration: 'Al-Majid', meaning: 'The Glorious / গৌরবময়'),
  AsmaulHusnaModel(number: 50, arabic: 'الْبَاعِثُ', transliteration: 'Al-Ba\'ith', meaning: 'The Resurrector / পুনরুত্থানকারী'),
  AsmaulHusnaModel(number: 51, arabic: 'الشَّهِيدُ', transliteration: 'Ash-Shahid', meaning: 'The Witness / সাক্ষী'),
  AsmaulHusnaModel(number: 52, arabic: 'الْحَقُّ', transliteration: 'Al-Haqq', meaning: 'The Truth / পরম সত্য'),
  AsmaulHusnaModel(number: 53, arabic: 'الْوَكِيلُ', transliteration: 'Al-Wakil', meaning: 'The Trustee / অভিভাবক'),
  AsmaulHusnaModel(number: 54, arabic: 'الْقَوِيُّ', transliteration: 'Al-Qawi', meaning: 'The Strong / মহাশক্তিশালী'),
  AsmaulHusnaModel(number: 55, arabic: 'الْمَتِينُ', transliteration: 'Al-Matin', meaning: 'The Firm / দৃঢ়'),
  AsmaulHusnaModel(number: 56, arabic: 'الْوَلِيُّ', transliteration: 'Al-Wali', meaning: 'The Protecting Friend / বন্ধু ও অভিভাবক'),
  AsmaulHusnaModel(number: 57, arabic: 'الْحَمِيدُ', transliteration: 'Al-Hamid', meaning: 'The Praiseworthy / প্রশংসার যোগ্য'),
  AsmaulHusnaModel(number: 58, arabic: 'الْمُحْصِي', transliteration: 'Al-Muhsi', meaning: 'The Counter / গণনাকারী'),
  AsmaulHusnaModel(number: 59, arabic: 'الْمُبْدِئُ', transliteration: 'Al-Mubdi\'', meaning: 'The Originator / সৃষ্টির উদ্যোক্তা'),
  AsmaulHusnaModel(number: 60, arabic: 'الْمُعِيدُ', transliteration: 'Al-Mu\'id', meaning: 'The Restorer / পুনরুদ্ধারকারী'),
  AsmaulHusnaModel(number: 61, arabic: 'الْمُحْيِي', transliteration: 'Al-Muhyi', meaning: 'The Giver of Life / জীবনদাতা'),
  AsmaulHusnaModel(number: 62, arabic: 'الْمُمِيتُ', transliteration: 'Al-Mumit', meaning: 'The Taker of Life / মৃত্যুদাতা'),
  AsmaulHusnaModel(number: 63, arabic: 'الْحَيُّ', transliteration: 'Al-Hayy', meaning: 'The Ever-Living / চিরজীবন্ত'),
  AsmaulHusnaModel(number: 64, arabic: 'الْقَيُّومُ', transliteration: 'Al-Qayyum', meaning: 'The Self-Subsisting / স্বনির্ভর'),
  AsmaulHusnaModel(number: 65, arabic: 'الْوَاجِدُ', transliteration: 'Al-Wajid', meaning: 'The Finder / সন্ধানকারী'),
  AsmaulHusnaModel(number: 66, arabic: 'الْمَاجِدُ', transliteration: 'Al-Majid', meaning: 'The Noble / মহৎ'),
  AsmaulHusnaModel(number: 67, arabic: 'الْوَاحِدُ', transliteration: 'Al-Wahid', meaning: 'The One / একক'),
  AsmaulHusnaModel(number: 68, arabic: 'الْأَحَدُ', transliteration: 'Al-Ahad', meaning: 'The Unique / অদ্বিতীয়'),
  AsmaulHusnaModel(number: 69, arabic: 'الصَّمَدُ', transliteration: 'As-Samad', meaning: 'The Eternal / চিরস্থায়ী'),
  AsmaulHusnaModel(number: 70, arabic: 'الْقَادِرُ', transliteration: 'Al-Qadir', meaning: 'The Omnipotent / সর্বক্ষমতাবান'),
  AsmaulHusnaModel(number: 71, arabic: 'الْمُقْتَدِرُ', transliteration: 'Al-Muqtadir', meaning: 'The Powerful / শক্তিমান'),
  AsmaulHusnaModel(number: 72, arabic: 'الْمُقَدِّمُ', transliteration: 'Al-Muqaddim', meaning: 'The Expediter / অগ্রগামী'),
  AsmaulHusnaModel(number: 73, arabic: 'الْمُؤَخِّرُ', transliteration: 'Al-Mu\'akhkhir', meaning: 'The Delayer / পশ্চাদগামী'),
  AsmaulHusnaModel(number: 74, arabic: 'الْأَوَّلُ', transliteration: 'Al-Awwal', meaning: 'The First / প্রথম'),
  AsmaulHusnaModel(number: 75, arabic: 'الْآخِرُ', transliteration: 'Al-Akhir', meaning: 'The Last / সর্বশেষ'),
  AsmaulHusnaModel(number: 76, arabic: 'الظَّاهِرُ', transliteration: 'Az-Zahir', meaning: 'The Manifest / প্রকাশিত'),
  AsmaulHusnaModel(number: 77, arabic: 'الْبَاطِنُ', transliteration: 'Al-Batin', meaning: 'The Hidden / গুপ্ত'),
  AsmaulHusnaModel(number: 78, arabic: 'الْوَالِي', transliteration: 'Al-Wali', meaning: 'The Governor / শাসনকর্তা'),
  AsmaulHusnaModel(number: 79, arabic: 'الْمُتَعَالِي', transliteration: 'Al-Muta\'ali', meaning: 'The Supreme / সর্বোচ্চ মহান'),
  AsmaulHusnaModel(number: 80, arabic: 'الْبَرُّ', transliteration: 'Al-Barr', meaning: 'The Source of Goodness / কল্যাণের উৎস'),
  AsmaulHusnaModel(number: 81, arabic: 'التَّوَّابُ', transliteration: 'At-Tawwab', meaning: 'The Ever-Relenting / তওবা কবুলকারী'),
  AsmaulHusnaModel(number: 82, arabic: 'الْمُنْتَقِمُ', transliteration: 'Al-Muntaqim', meaning: 'The Avenger / প্রতিশোধকারী'),
  AsmaulHusnaModel(number: 83, arabic: 'الْعَفُوُّ', transliteration: 'Al-\'Afuw', meaning: 'The Pardoner / মাফকারী'),
  AsmaulHusnaModel(number: 84, arabic: 'الرَّؤُوفُ', transliteration: 'Ar-Ra\'uf', meaning: 'The Compassionate / দয়াবান'),
  AsmaulHusnaModel(number: 85, arabic: 'مَالِكُ الْمُلْكِ', transliteration: 'Malik-ul-Mulk', meaning: 'Owner of Sovereignty / সার্বভৌম মালিক'),
  AsmaulHusnaModel(number: 86, arabic: 'ذُو الْجَلَالِ وَالْإِكْرَامِ', transliteration: 'Dhul-Jalali-wal-Ikram', meaning: 'Lord of Majesty and Honour / মহিমা ও সম্মানের অধিপতি'),
  AsmaulHusnaModel(number: 87, arabic: 'الْمُقْسِطُ', transliteration: 'Al-Muqsit', meaning: 'The Equitable / ন্যায়বিচারক'),
  AsmaulHusnaModel(number: 88, arabic: 'الْجَامِعُ', transliteration: 'Al-Jami\'', meaning: 'The Gatherer / একত্রকারী'),
  AsmaulHusnaModel(number: 89, arabic: 'الْغَنِيُّ', transliteration: 'Al-Ghani', meaning: 'The Self-Sufficient / অমুখাপেক্ষী'),
  AsmaulHusnaModel(number: 90, arabic: 'الْمُغْنِي', transliteration: 'Al-Mughni', meaning: 'The Enricher / সম্পদশালী কারক'),
  AsmaulHusnaModel(number: 91, arabic: 'الْمَانِعُ', transliteration: 'Al-Mani\'', meaning: 'The Preventer / বাধাদানকারী'),
  AsmaulHusnaModel(number: 92, arabic: 'الضَّارُّ', transliteration: 'Ad-Darr', meaning: 'The Distresser / কষ্টদানকারী'),
  AsmaulHusnaModel(number: 93, arabic: 'النَّافِعُ', transliteration: 'An-Nafi\'', meaning: 'The Benefiter / উপকারকারী'),
  AsmaulHusnaModel(number: 94, arabic: 'النُّورُ', transliteration: 'An-Nur', meaning: 'The Light / আলো'),
  AsmaulHusnaModel(number: 95, arabic: 'الْهَادِي', transliteration: 'Al-Hadi', meaning: 'The Guide / পথপ্রদর্শক'),
  AsmaulHusnaModel(number: 96, arabic: 'الْبَدِيعُ', transliteration: 'Al-Badi\'', meaning: 'The Incomparable / অতুলনীয় সৃষ্টিকর্তা'),
  AsmaulHusnaModel(number: 97, arabic: 'الْبَاقِي', transliteration: 'Al-Baqi', meaning: 'The Ever-Enduring / চিরস্থায়ী'),
  AsmaulHusnaModel(number: 98, arabic: 'الْوَارِثُ', transliteration: 'Al-Warith', meaning: 'The Inheritor / উত্তরাধিকারী'),
  AsmaulHusnaModel(number: 99, arabic: 'الرَّشِيدُ', transliteration: 'Ar-Rashid', meaning: 'The Guide to the Right Path / সঠিক পথের দিশারী'),
];
